name: passwordmaster
description: "SecureVault - Premium Password Manager"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  sqflite_sqlcipher: ^3.0.1
  path_provider: ^2.1.6
  path: ^1.9.1
  file_picker: ^11.0.2
  encrypt: ^5.0.3
  crypto: ^3.0.3
  open_filex: ^4.5.0
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.2
  http: ^1.2.1
  share_plus: ^12.0.2
  flutter_file_dialog: ^3.3.1
  local_auth: ^3.0.1
  flutter_secure_storage: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
